### ISSUE TITLE
Plugin disabled in 4D v18R3

### ISSUE THREAD

**Issue by nilskoll** [miyako/4d-plugin-ql#1]
I installed the plugin bundle from the QL.dmg and inside 4D v18R3, the plugin (version 2.0.1) shows as Disabled (the executable could not be loaded). Any ideas?

Thanks in advance.

Nils

**Comment by miyako** [comment]
What is the macOS version? 

It might be a notarisation/stapler error on my part,  but the plugin uses a private API, so it may only work on specific macOS versions.

This one only uses standard APIs:

https://github.com/miyako/4d-plugin-ql-light

**Comment by nilskoll** [comment]
Hi, that was quick!
I'm on Mojave 10.14.6.

Best regards
Nils Kollandsrud

**Comment by nilskoll** [comment]
I tried the light version also, same issue:


Best regards
Nils Kollandsrud

**Comment by miyako** [comment]
I tested on Catalina+18 R3 and it works all right.

I think Mojave is the problem.

**Comment by nilskoll** [comment]
Yes, I tested on Catalina (the server is running 10.15.5) and the plugin works great!
I'll just use the old version on pre-Catalina servers.

Thanks for the quick response!


Best regards
Nils Kollandsrud

**Comment by miyako** [comment]
The plugin was linked to [QuickLookThumbnailing](https://developer.apple.com/documentation/quicklookthumbnailing?language=objc) framework, which is 10.15+, **even though it doesn't need it.**

I will recompile it without the link.

**Comment by miyako** [comment]
https://github.com/miyako/4d-plugin-ql/releases/tag/2.1.0

**Comment by nilskoll** [comment]
Thanks! Tested it on Mojave and the plugin is now enabled/working.
