### ISSUE TITLE
Does this plugin require 4D Write, and can it preview EML files?

### ISSUE THREAD

**Issue by cdf1982** [miyako/4d-plugin-ql#2]
Hi and thank you for this plugin, it looks awesome and exactly what we needed.

Per the subject, I have two questions: **does this plugin require 4D Write** (it appears to do so, while the [light version](https://github.com/miyako/4d-plugin-ql-light) doesn't, but in my testing does only generate an image preview of the passed in document)?

**Can it preview .eml email files, like macOS can in QuickLook?** That format doesn't seem listed among the supported formats on Apple's own [docs](https://developer.apple.com/documentation/quicklook/qlpreviewcontroller), and indeed testing a QuickLook preview with the light plugin only generates an image of the eml file icon.

Thanks in advance!

**Comment by miyako** [comment]
4D Write is not required.

the difference between light and regular is that light uses official Apple API, while regular uses undocumented API which changes from time to time.

v2 may work better on newer OS.

**Comment by miyako** [comment]
https://github.com/miyako/4d-plugin-ql-v2

**Comment by cdf1982** [comment]
Thank you so much!
We're doing some testing with the v2, sadly it seems .eml files only preview with an icon and not the actual email content; it had to be expected considering Apple is not listing that file format in the documentation for `QLPreviewController`, but yours is nevertheless an amazing plugin, thank you for your work!
